import java.awt.event.*;
/**
 *
 * @author Samantha
 */
public class ProgUI extends javax.swing.JFrame implements ActionListener, CommonData{
    // Variables declaration - do not modify
    private javax.swing.JButton jbGenerate;
    private javax.swing.JComboBox jcbMajor;
    private javax.swing.JComboBox jcbMinor;
    private javax.swing.JPanel jpData;
    private javax.swing.JPanel jpOptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
    private String username = "guest";

   /**
   * Creates new form progUI
   */
   public ProgUI() {
      initComponents();
      setVisible(true);
   }

   /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {
      jpOptions = new javax.swing.JPanel();
      jbGenerate = new javax.swing.JButton();
      jcbMinor = new javax.swing.JComboBox();
      jcbMajor = new javax.swing.JComboBox();
      jpData = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(204, 255, 255));

      jpOptions.setBackground(new java.awt.Color(255, 255, 204));
      jpOptions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      jpOptions.setName("Options"); // NOI18N

      jbGenerate.setBackground(new java.awt.Color(204, 255, 255));
      jbGenerate.setText("Generate Data");
      jbGenerate.setName(""); // NOI18N

      jcbMinor.setBackground(new java.awt.Color(204, 255, 255));
      jcbMinor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Minor", "Computer Science", "Game Design" }));

      jcbMajor.setBackground(new java.awt.Color(204, 255, 255));
      jcbMajor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Major", "Information Technology", "Computer Science" }));

      javax.swing.GroupLayout jpOptionsLayout = new javax.swing.GroupLayout(jpOptions);
      jpOptions.setLayout(jpOptionsLayout);
      jpOptionsLayout.setHorizontalGroup(
          jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jpOptionsLayout.createSequentialGroup()
              .addContainerGap()
              .addGroup(jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOptionsLayout.createSequentialGroup()
                      .addGap(0, 0, Short.MAX_VALUE)
                      .addComponent(jbGenerate))
                  .addComponent(jcbMinor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jcbMajor, 0, 197, Short.MAX_VALUE))
              .addContainerGap())
      );
      jpOptionsLayout.setVerticalGroup(
          jpOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jpOptionsLayout.createSequentialGroup()
              .addGap(23, 23, 23)
              .addComponent(jcbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jcbMinor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jbGenerate)
              .addContainerGap())
      );

        jpData.setBackground(new java.awt.Color(255, 255, 204));
        jpData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpData.setName("output"); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jpDataLayout = new javax.swing.GroupLayout(jpData);
        jpData.setLayout(jpDataLayout);
        jpDataLayout.setHorizontalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDataLayout.setVerticalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
       jbGenerate.addActionListener(this);
       jTextArea1.append("Welcome to YourPlan, \nplease select a major and minor,\nwe will generate the courses required for this plan!");
       pack();
   }
 
   public void actionPerformed(ActionEvent ae) {
      if( ae.getActionCommand().equals("Generate Data") ){
         String major;
         String minor;
         if(jcbMajor.getSelectedItem().equals("Information Technology")){
            major = "Information Technology";  
         }else if(jcbMajor.getSelectedItem().equals("Computer Science")){
            major = "Computer Science";
         }else{
            major = "major";
         }
         
         if(jcbMinor.getSelectedItem().equals("Game Design")){
            minor = "Game Design";  
         }else if(jcbMinor.getSelectedItem().equals("Computer Science")){
            minor = "Computer Science";
         }else{
            minor = "minor";
         }
         Intermediary newData = new Intermediary( username, major, minor, NONE );
         jTextArea1.append( newData.getNextOutput() );
     } 
   }
}

